# C.D 가 넘겨준 파일을 EC2에서 어떻게 처리할 것인지에 대한 설정 파일
# C.D 에서 EC2 상의 이동 -> .travis.yml 에서 zip 파일로 이동시킴
# EC2 상의 이동 -> appspec.yml 에서 C.D 에서 전해준 파일을 destination 으로 이동
version: 0.0 # CodeDeploy 버전 (0.0 외에 다른 버전 사용하면 오류)
os: linux
files:
  - source: / # CodeDeploy 에서 전달해준 파일 : 전체 파일(/)
    destination: /home/ec2-user/app/step3/zip/ # source 에서 지정한 파일을 받을 위치. 이후 destination 에서 옮긴 파일들로 진행
    overwrite: yes # 기존에 파일이 있으면 덮어쓰기

permissions: # C.D 에서 EC2로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks: # 배포단계에서 실행할 명령어
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료합니다.
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링 부트를 시작합니다.
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인 합니다.
      timeout: 60
      runas: ec2-user