package com.susu.book.springboot.domain.posts;

import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Getter
@NoArgsConstructor // 기본생성자
@Entity // 테이블 posts와 매칭
public class Posts {
    /*
    *   Hibernate: create table posts (id bigint generated by default as identity, author varchar(255), content TEXT not null, title varchar(500) not null, primary key (id))
    * */
    @Id // 해당 테이블의 PK
    @GeneratedValue(strategy = GenerationType.IDENTITY) // PK생성 규칙 : auto increment
    private Long id;

    @Column(length = 500, nullable = false)
    private String title;

    @Column(columnDefinition = "TEXT", nullable = false)
    private String content;

    private String author;

    @Builder // 디자인 패턴 : 빌더 패턴 (setter 메소드나, 매개변수 가진 생성자 대신 사용 : 실행시 변수전달 순서에서 자유로움, 메소드로 전달)
    public Posts(String title, String content, String author){
        this.title=title;
        this.content=content;
        this.author=author;
    }


}
